version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
<<<<<<< HEAD
  cache_timestamp: '2025-11-25 14:16:10'
=======
  cache_timestamp: '2025-11-25 14:31:45'
>>>>>>> e3487346b666d532226f18511b185c8bf324eb0e
  filters:
  - crud
expanded:
- poo@campanha-principal
- poo@bloco_d-crud-com-mapas-e-enumerações
<<<<<<< HEAD
tasks:
  poo@contato: '{rate:60}'
=======
tasks: {}
>>>>>>> e3487346b666d532226f18511b185c8bf324eb0e
flags:
  quests: 0
  tracks: 0
  tasks: 0
  graph: 1
  xray: 0
lang: py
selected: poo@contato
